### ISSUE TITLE
Hitting OpenAI GPT4 token limit

### ISSUE THREAD

**Issue by pytony17** [docugami/kgrag-datasets#4]
Love the project here. I've been working to enable complex Q&A over SEC 10-Q and 10-K docs for a while. I ran the code exactly as you provided. Unfortunately, when it gets to the part where it creates the prompt chain and calls the model, it dies because it exceeds the OpenAI token limit (8192 I think). How did you overcome the token issue?

**Comment by tjaffri** [comment]
Hi @pytony17 thanks for commenting! This repository is only focused on datasets... the sample code provided is for reference just to get you started. Which code are you talking about? I assume this notebook? https://github.com/docugami/KG-RAG-datasets/blob/main/sec-10-q/process_docs.ipynb

This notebook is how the answers were initially generated (before human review/corrections). The process we followed is outlined in the [README](https://github.com/docugami/KG-RAG-datasets/blob/main/sec-10-q/README.md) for the SEC 10-Q datasets. We shared this notebook for completeness, but please note that you should not be required to run this notebook just to use the dataset.

Regardless, if you still want to run this notebook you can try a few things:

1. In cell 8, make sure you are using the same model we are using i.e. gpt-4-1106-preview. This model has a much larger context limit of 128k tokens. Reference: https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
2. In the last cell you will notice this line: `doc_text = doc_text[:40 * 1024 * 4]  # ~40k tokens, approximately, per document max`. You can try to reduce the per document token count although this amount should fit comfortably in the gpt-4-1106-preview context limit.

Hope this helps!
